# Generated by Django 2.2.4 on 2019-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='Doctor', editable=False, max_length=7),
        ),
    ]
